spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: redis
      port: 6379
      password: Z2Zsa2pnbGZk
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public
server:
  port: 8099

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30

springdoc:
  override-with-generic-response: false