spring:
  datasource:
    url: jdbc:postgresql://localhost:3036/employees_db?currentSchema=employees_db
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: employees_db
server:
  port: 8099

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: amZhbGRqZmFsa2ZqZGFzO2xramRza2xhamZsa2RzamZsaztkamtsc2FmbGtmamRsYWtzamZrbGFqZHNsa2ZhamxrO2RzZmxhZmphbGRrcw==
    access: 3600000
    refresh: 2592000000

springdoc:
  override-with-generic-response: false