apiVersion: v1
kind: Service
metadata:
  name: employee-assessment
  labels:
    app.kubernetes.io/name: employee-assessment
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8099
  selector:
    app.kubernetes.io/name: employee-assessment