apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  labels:
    app.kubernetes.io/name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pg
    spec:
      containers:
        - name: pg
          image: postgres:16
          ports:
            - containerPort: 5432
              name: pg
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DATABASE
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_SCHEMA
                  name: env
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: env